AWSTemplateFormatVersion: 2010-09-09
Description: "API Gateway"
Parameters:
  FunctionName:
    Type: String
    Description: "Lambda Function Name"
    Default: "test"
  ApiName:
    Type: String
    Description: "name of API"
    Default: "api-test"
  ResourceName:
    Type: String
    Description: "name of Resource"
    Default: "hoge"
Resources:
  Api:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: !Sub "${ApiName}"
  Resource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      RestApiId: !Ref Api
      ParentId: !GetAtt Api.RootResourceId  
      PathPart: !Sub "${ResourceName}"
  LambdaPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !Sub "${FunctionName}"
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
  ResourceMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      RestApiId: !Ref Api
      ResourceId: !Ref Resource
      AuthorizationType: "None"
      HttpMethod: "GET"
      Integration:
        Type: "AWS_PROXY" # lambdaプロキシ統合の場合はこの値にする
        IntegrationHttpMethod: "POST" # GETを指定していてもPOSTという項目にしないとエラーになる
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FunctionName}/invocations"
    DependsOn: "LambdaPermission"
